<a href="https://colab.research.google.com/github/marciapaulasv-coder/TechChalenge/blob/main/02_preprocessamento.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd
from sklearn import*

df = pd.read_csv('base_modelagem.csv')

df.shape

(36457, 22)

**1) Verificação das colunas existentes na base**

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36457 entries, 0 to 36456
Data columns (total 22 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   ID                   36457 non-null  int64
 1   CODE_GENDER          36457 non-null  int64
 2   FLAG_OWN_CAR         36457 non-null  int64
 3   FLAG_OWN_REALTY      36457 non-null  int64
 4   CNT_CHILDREN         36457 non-null  int64
 5   AMT_INCOME_TOTAL     36457 non-null  float64
 6   NAME_INCOME_TYPE     36457 non-null  object
 7   NAME_EDUCATION_TYPE  36457 non-null  object
 8   NAME_FAMILY_STATUS   36457 non-null  object
 9   NAME_HOUSING_TYPE    36457 non-null  object
 10  DAYS_BIRTH           36457 non-null  int64
 11  DAYS_EMPLOYED        36457 non-null  int64
 12  FLAG_MOBIL           36457 non-null  int64
 13  FLAG_WORK_PHONE      36457 non-null  int64
 14  FLAG_PHONE           36457 non-null  int64
 15  FLAG_EMAIL           36457 non-null  int64
 16  OCCUPATION_TYPE      25134 non-null  object
 17  CNT_FAM_MEMBERS      36457 non-null  float64
 18  TARGET               36457 non-null  int64
 19  PERFIL               36457 non-null  int64
 20  IDADE                36457 non-null  int64
 21  ANOS_EMPREGADO       30322 non-null  float64
dtypes: float64(3), int64(14), object(5)
memory usage: 6.1+ MB

In [3]:
df_modelo = df.drop(columns=['ID', 'DAYS_BIRTH', 'DAYS_EMPLOYED', 'PERFIL'])

df_modelo.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36457 entries, 0 to 36456
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   CODE_GENDER          36457 non-null  int64
 1   FLAG_OWN_CAR         36457 non-null  int64
 2   FLAG_OWN_REALTY      36457 non-null  int64
 3   CNT_CHILDREN         36457 non-null  int64
 4   AMT_INCOME_TOTAL     36457 non-null  float64
 5   NAME_INCOME_TYPE     36457 non-null  object
 6   NAME_EDUCATION_TYPE  36457 non-null  object
 7   NAME_FAMILY_STATUS   36457 non-null  object
 8   NAME_HOUSING_TYPE    36457 non-null  object
 9   FLAG_MOBIL           36457 non-null  int64
 10  FLAG_WORK_PHONE      36457 non-null  int64
 11  FLAG_PHONE           36457 non-null  int64
 12  FLAG_EMAIL           36457 non-null  int64
 13  OCCUPATION_TYPE      25134 non-null  object
 14  CNT_FAM_MEMBERS      36457 non-null  float64
 15  TARGET               36457 non-null  int64
 16  IDADE                36457 non-null  int64
 17  ANOS_EMPREGADO       30322 non-null  float64
dtypes: float64(3), int64(10), object(5)
memory usage: 5.0+ MB

**Conclusão:** foram excluídas as colunas ID, por representar apenas a identificação do cliente, e PERFIL, por representar a mesma informação do TARGET. Também foram excluídas DAYS_BIRTH e DAYS_EMPLOYED, pois suas informações já estão representadas pelas variáveis IDADE e ANOS_EMPREGADO, respectivamente.

**2) Verificação de IDs duplicados**

In [4]:
print('Quantidade de registros:', len(df))
print('Quantidade de IDs únicos:', df['ID'].nunique())
print('Quantidade de IDs duplicados:', df['ID'].duplicated().sum())

Quantidade de registros: 36457
Quantidade de IDs únicos: 36457
Quantidade de IDs duplicados: 0

**Conclusão:** A base de modelagem possui 36.457 registros e 36.457 IDs únicos, não sendo identificados clientes duplicados.

**3) Tratamento de Valores Nulos**

**Coluna "OCCUPATION_TYPE"**

In [5]:
df_modelo['OCCUPATION_TYPE'].value_counts(dropna=False)

OCCUPATION_TYPE
NaN                      11323
Laborers                  6211
Core staff                3591
Sales staff               3485
Managers                  3012
Drivers                   2138
High skill tech staff     1383
Accountants               1241
Medicine staff            1207
Cooking staff              655
Security staff             592
Cleaning staff             551
Private service staff      344
Low-skill Laborers         175
Waiters/barmen staff       174
Secretaries                151
HR staff                    85
Realty agents               79
IT staff                    60
Name: count, dtype: int64

In [6]:
df_modelo['OCCUPATION_TYPE'] = df_modelo['OCCUPATION_TYPE'].fillna('Não informado')
df_modelo['OCCUPATION_TYPE'].value_counts()

OCCUPATION_TYPE
Não informado            11323
Laborers                  6211
Core staff                3591
Sales staff               3485
Managers                  3012
Drivers                   2138
High skill tech staff     1383
Accountants               1241
Medicine staff            1207
Cooking staff              655
Security staff             592
Cleaning staff             551
Private service staff      344
Low-skill Laborers         175
Waiters/barmen staff       174
Secretaries                151
HR staff                    85
Realty agents               79
IT staff                    60
Name: count, dtype: int64

**Conclusão:** A variável OCCUPATION_TYPE apresentou 11.323 valores ausentes, ou seja 31% da base. Como a quantia é muito significativa, optou-se por não excluir a informação e foi criada a categoria “Não informado”.

**Coluna "ANOS_EMPREGADO"**

In [7]:
df[df['ANOS_EMPREGADO'].isna()]['NAME_INCOME_TYPE'].value_counts(dropna=False)

NAME_INCOME_TYPE
Pensioner    6135
Name: count, dtype: int64

In [8]:
df_modelo['ANOS_EMPREGADO'] = df_modelo['ANOS_EMPREGADO'].fillna(0)
df_modelo['ANOS_EMPREGADO'].isna().sum()

np.int64(0)

**Conclusão:** Os valores ausentes dessa variável correspondem aos clientes pensionistas e foram gerados durante a transformação da variável original DAYS_EMPLOYED, que apresentava o código especial 365243. Para esses casos, foi atribuído o valor 0. Entendendo-se que por não estarem trabalhando, não tem tempo de emprego.

In [9]:
df_modelo.isna().sum()

CODE_GENDER            0
FLAG_OWN_CAR           0
FLAG_OWN_REALTY        0
CNT_CHILDREN           0
AMT_INCOME_TOTAL       0
NAME_INCOME_TYPE       0
NAME_EDUCATION_TYPE    0
NAME_FAMILY_STATUS     0
NAME_HOUSING_TYPE      0
FLAG_MOBIL             0
FLAG_WORK_PHONE        0
FLAG_PHONE             0
FLAG_EMAIL             0
OCCUPATION_TYPE        0
CNT_FAM_MEMBERS        0
TARGET                 0
IDADE                  0
ANOS_EMPREGADO         0
dtype: int64

**4) Identificação das Variáveis Categóricas na base**

In [10]:
colunas_categoricas = df_modelo.select_dtypes(include='object').columns

for coluna in colunas_categoricas:
    print(f'\n{coluna}')
    print(df_modelo[coluna].value_counts())

NAME_INCOME_TYPE
NAME_INCOME_TYPE
Working                 18819
Commercial associate     8490
Pensioner                6152
State servant            2985
Student                    11
Name: count, dtype: int64

NAME_EDUCATION_TYPE
NAME_EDUCATION_TYPE
Secondary / secondary special    24777
Higher education                  9864
Incomplete higher                 1410
Lower secondary                    374
Academic degree                     32
Name: count, dtype: int64

NAME_FAMILY_STATUS
NAME_FAMILY_STATUS
Married                 25048
Single / not married     4829
Civil marriage           2945
Separated                2103
Widow                    1532
Name: count, dtype: int64

NAME_HOUSING_TYPE
NAME_HOUSING_TYPE
House / apartment      32548
With parents            1776
Municipal apartment     1128
Rented apartment         575
Office apartment         262
Co-op apartment          168
Name: count, dtype: int64

OCCUPATION_TYPE
OCCUPATION_TYPE
Não informado            11323
Laborers                  6211
Core staff                3591
Sales staff               3485
Managers                  3012
Drivers                   2138
High skill tech staff     1383
Accountants               1241
Medicine staff            1207
Cooking staff              655
Security staff             592
Cleaning staff             551
Private service staff      344
Low-skill Laborers         175
Waiters/barmen staff       174
Secretaries                151
HR staff                    85
Realty agents               79
IT staff                    60
Name: count, dtype: int64

**5) Separação das Bases de Dados**

In [11]:
#Separação de X/Y

X = df_modelo.drop(columns='TARGET')
y = df_modelo['TARGET']

In [12]:
# Separação treino/teste
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.30, random_state=42, stratify=y)

**6) Transformação de Variáveis Categóricas em Numéricas**

In [13]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(drop='first', handle_unknown='ignore', sparse_output=False)

In [14]:
X_train_encoded = encoder.fit_transform(X_train[colunas_categoricas])

X_train_encoded.shape

(25519, 35)

In [15]:
X_test_encoded = encoder.transform(X_test[colunas_categoricas])

X_test_encoded.shape

(10938, 35)

In [16]:
colunas_numericas = X_train.select_dtypes(exclude='object').columns

colunas_numericas

Index(['CODE_GENDER', 'FLAG_OWN_CAR', 'FLAG_OWN_REALTY', 'CNT_CHILDREN',
       'AMT_INCOME_TOTAL', 'FLAG_MOBIL', 'FLAG_WORK_PHONE', 'FLAG_PHONE',
       'FLAG_EMAIL', 'CNT_FAM_MEMBERS', 'IDADE', 'ANOS_EMPREGADO'],
      dtype='object')

In [21]:
nomes_colunas_encoded = encoder.get_feature_names_out(colunas_categoricas)

nomes_colunas_encoded

array(['NAME_INCOME_TYPE_Pensioner', 'NAME_INCOME_TYPE_State servant',
       'NAME_INCOME_TYPE_Student', 'NAME_INCOME_TYPE_Working',
       'NAME_EDUCATION_TYPE_Higher education',
       'NAME_EDUCATION_TYPE_Incomplete higher',
       'NAME_EDUCATION_TYPE_Lower secondary',
       'NAME_EDUCATION_TYPE_Secondary / secondary special',
       'NAME_FAMILY_STATUS_Married', 'NAME_FAMILY_STATUS_Separated',
       'NAME_FAMILY_STATUS_Single / not married',
       'NAME_FAMILY_STATUS_Widow', 'NAME_HOUSING_TYPE_House / apartment',
       'NAME_HOUSING_TYPE_Municipal apartment',
       'NAME_HOUSING_TYPE_Office apartment',
       'NAME_HOUSING_TYPE_Rented apartment',
       'NAME_HOUSING_TYPE_With parents', 'OCCUPATION_TYPE_Cleaning staff',
       'OCCUPATION_TYPE_Cooking staff', 'OCCUPATION_TYPE_Core staff',
       'OCCUPATION_TYPE_Drivers', 'OCCUPATION_TYPE_HR staff',
       'OCCUPATION_TYPE_High skill tech staff',
       'OCCUPATION_TYPE_IT staff', 'OCCUPATION_TYPE_Laborers',
       'OCCUPATION_TYPE_Low-skill Laborers', 'OCCUPATION_TYPE_Managers',
       'OCCUPATION_TYPE_Medicine staff', 'OCCUPATION_TYPE_Não informado',
       'OCCUPATION_TYPE_Private service staff',
       'OCCUPATION_TYPE_Realty agents', 'OCCUPATION_TYPE_Sales staff',
       'OCCUPATION_TYPE_Secretaries', 'OCCUPATION_TYPE_Security staff',
       'OCCUPATION_TYPE_Waiters/barmen staff'], dtype=object)

In [18]:
X_train_encoded = pd.DataFrame(X_train_encoded, columns=nomes_colunas_encoded, index=X_train.index)

X_train_encoded.head()

,NAME_INCOME_TYPE_Pensioner,NAME_INCOME_TYPE_State servant,NAME_INCOME_TYPE_Student,NAME_INCOME_TYPE_Working,NAME_EDUCATION_TYPE_Higher education,NAME_EDUCATION_TYPE_Incomplete higher,NAME_EDUCATION_TYPE_Lower secondary,NAME_EDUCATION_TYPE_Secondary / secondary special,NAME_FAMILY_STATUS_Married,NAME_FAMILY_STATUS_Separated,...,OCCUPATION_TYPE_Low-skill Laborers,OCCUPATION_TYPE_Managers,OCCUPATION_TYPE_Medicine staff,OCCUPATION_TYPE_Não informado,OCCUPATION_TYPE_Private service staff,OCCUPATION_TYPE_Realty agents,OCCUPATION_TYPE_Sales staff,OCCUPATION_TYPE_Secretaries,OCCUPATION_TYPE_Security staff,OCCUPATION_TYPE_Waiters/barmen staff
11857,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10943,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
13820,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
5341,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
33119,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0

In [19]:
X_test_encoded = pd.DataFrame(X_test_encoded, columns=nomes_colunas_encoded, index=X_test.index)

X_test_encoded.head()

,NAME_INCOME_TYPE_Pensioner,NAME_INCOME_TYPE_State servant,NAME_INCOME_TYPE_Student,NAME_INCOME_TYPE_Working,NAME_EDUCATION_TYPE_Higher education,NAME_EDUCATION_TYPE_Incomplete higher,NAME_EDUCATION_TYPE_Lower secondary,NAME_EDUCATION_TYPE_Secondary / secondary special,NAME_FAMILY_STATUS_Married,NAME_FAMILY_STATUS_Separated,...,OCCUPATION_TYPE_Low-skill Laborers,OCCUPATION_TYPE_Managers,OCCUPATION_TYPE_Medicine staff,OCCUPATION_TYPE_Não informado,OCCUPATION_TYPE_Private service staff,OCCUPATION_TYPE_Realty agents,OCCUPATION_TYPE_Sales staff,OCCUPATION_TYPE_Secretaries,OCCUPATION_TYPE_Security staff,OCCUPATION_TYPE_Waiters/barmen staff
35916,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
30233,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
7234,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0
22629,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
18252,0.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [22]:
# Junção das variáveis numéricas com as variáveis categóricas transformadas

X_train_preparado = pd.concat([X_train[colunas_numericas], X_train_encoded], axis=1)

X_train_preparado.shape

(25519, 47)

In [23]:
# Junção das variáveis numéricas com as variáveis categóricas transformadas - teste

X_test_preparado = pd.concat([X_test[colunas_numericas], X_test_encoded], axis=1)

X_test_preparado.shape

(10938, 47)

In [25]:
# Variáveis numéricas que serão padronizadas
colunas_padronizar = ['CNT_CHILDREN','AMT_INCOME_TOTAL', 'CNT_FAM_MEMBERS', 'IDADE', 'ANOS_EMPREGADO']

**7) Padronização de Variáveis Numéricas**

In [26]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train_preparado[colunas_padronizar] = scaler.fit_transform(X_train_preparado[colunas_padronizar])

X_test_preparado[colunas_padronizar] = scaler.transform(X_test_preparado[colunas_padronizar])

In [27]:
X_train_preparado[colunas_padronizar].describe().round(2)

,CNT_CHILDREN,AMT_INCOME_TOTAL,CNT_FAM_MEMBERS,IDADE,ANOS_EMPREGADO
count,25519.00,25519.00,25519.00,25519.00,25519.00
mean,-0.00,0.00,0.00,0.00,0.00
std,1.00,1.00,1.00,1.00,1.00
min,-0.57,-1.56,-1.31,-2.02,-0.93
25%,-0.57,-0.64,-0.21,-0.80,-0.76
50%,-0.57,-0.29,-0.21,-0.10,-0.27
75%,0.77,0.37,0.88,0.85,0.40
max,24.89,13.55,19.48,2.16,5.72

In [28]:
# Verificação das dimensões das bases finais

print('Treino:', X_train_preparado.shape)
print('Teste:', X_test_preparado.shape)

Treino: (25519, 47)
Teste: (10938, 47)

In [29]:
# Verificação de valores nulos nas bases finais

print('Nulos no treino:', X_train_preparado.isna().sum().sum())
print('Nulos no teste:', X_test_preparado.isna().sum().sum())

Nulos no treino: 0
Nulos no teste: 0

In [30]:
# Verificação dos tipos das variáveis

X_train_preparado.dtypes.value_counts()

float64    40
int64       7
Name: count, dtype: int64

**Conclusão do Pré-processamento**

Nesta etapa, foram tratadas as variáveis com valores nulos, excluídas as colunas que não seriam utilizadas e transformadas as variáveis categóricas por meio do One-Hot Encoding.

A base foi dividida em conjuntos de treino e teste, preservando a proporção das classes do TARGET. As variáveis numéricas selecionadas foram padronizadas com o StandardScaler, utilizando os dados de treino como referência para evitar vazamento de dados.

Ao final, as bases de treino e teste ficaram com 47 variáveis, sem valores nulos e apenas com dados numéricos.